type ItemSize {
	id: ID!
	item: Item!
	price: Float
	size: String
	photo: String
	created_at: String
	updated_at: String
}

type Query {
  item_sizes: [ItemSize!]!
  item_size(id: ID!): ItemSize!
}

type Mutation {
  createItemSize(input: CreateItemSizeInput!): ItemSize!
  updateItemSize(id: ID!, input: UpdateItemSizeInput!): ItemSize!
  removeItemSize(id: ID!): ItemSize!
}

type Subscription {
  itemSizeCreated: Item!
}

input CreateItemSizeInput {
	item_id: ID!
	price: Float!
	size: String!
	photo: String
}

input UpdateItemSizeInput {
	item_id: ID
	price: Float
	size: String
	photo: String
}